// Shell copy — the ES/EN dictionaries for the K4 information architecture.
//
// ONE document language at a time. These dictionaries cover the surfaces K4 owns
// (mode control, scope & freshness rail, evidence drawer, section structure,
// layer-scoped controls and the static panel labels it re-homed). They are loaded
// through the shared createI18n mechanism in js/i18n.js, exactly like the Bridge,
// hospitality and origin dictionaries, so there is one language-selection and
// fallback path and no render function holds a literal string for a new surface.
//
// Official source VALUES are never translated here: an interpretation ceiling or
// a publisher's own wording is carried verbatim from data/source_registry.json.
// Only our labels around them change language.

const SHELL_DICTIONARIES = Object.freeze({
  en: Object.freeze({
    "mode.place": "Place", "mode.compare": "Compare", "mode.city": "City",
    "mode.q.place": "What does the evidence say about this place?",
    "mode.q.compare": "How do two Lens circles read against each other?",
    "mode.q.city": "What is the municipality-wide context?",
    "mode.announce": "Mode",
    "sec.detail": "Detail", "sec.evidence": "Evidence & limits", "sec.controls": "Controls",
    "sec.withinLens": "Within the Lens", "sec.compare": "Lens A ↔ Lens B",
    "rail.reference": "Reference", "rail.notPublished": "not published", "rail.state": "State",
    "rail.oldest": "Oldest reference date among the sources contributing to what is on screen",
    "rail.open": "Open the evidence for",
    "rail.lens": "Lens", "rail.locating": "locating…", "rail.barrio": "barrio",
    "rail.multiple": "several publisher states",
    "scope.LENS_CIRCLE": "Lens circle", "scope.OFFICIAL_BARRIO": "Official barrio",
    "scope.OFFICIAL_DISTRICT": "Official district", "scope.MUNICIPALITY": "Municipality",
    "scope.POINT_OBSERVATION": "Point observation", "scope.BOUNDED_STUDY_AREA": "Study area",
    "scope.PLANNING_AMBITO": "Planning ámbito", "scope.EXECUTION_UNIT": "Execution unit",
    "scope.DEVELOPMENT_STAGE_AREA": "Development stage area", "scope.PARCEL": "Parcel",
    "scope.ADDRESS_POINT": "Address point", "scope.WORK_GEOMETRY": "Work geometry",
    "scope.LENS_INTERSECT_AMBITO": "Lens ∩ ámbito",
    "state.DEFINITIVE": "Definitive", "state.PROVISIONAL": "Provisional",
    "state.WITHHELD_BY_PUBLISHER": "Withheld by publisher",
    "state.NOT_DECLARED_BY_PUBLISHER": "Not declared by publisher",
    "freq.DAILY": "Daily", "freq.WEEKLY": "Weekly", "freq.MONTHLY": "Monthly",
    "freq.BIMONTHLY": "Bimonthly", "freq.QUARTERLY": "Quarterly", "freq.SEMESTRAL": "Semestral",
    "freq.ANNUAL": "Annual", "freq.IRREGULAR": "Irregular",
    "freq.DECLARED_UNDEFINED": "Publisher declares it undefined",
    "freq.NONE_DECLARED": "No frequency declared",
    "drawer.title": "Evidence & limits", "drawer.close": "Close",
    "drawer.empty": "No evidence records for this selection.",
    "drawer.filter.all": "All evidence on screen in this mode",
    "drawer.filter.scope": "Filtered to scope",
    "drawer.notes.area": "Source & interpretation · Administrative area",
    "drawer.notes.destination": "Source & interpretation · Destination context",
    "drawer.legend": "Comparison halo legend", "drawer.sources": "Sources",
    "drawer.sourcesOf": "Source",
    "reading.label": "Reading", "reading.citizen": "Citizen", "reading.analyst": "Analyst",
    "f.source": "Source", "f.authority": "Authority", "f.scope": "Scope", "f.scopeDefinition": "Scope definition",
    "f.unit": "Unit", "f.reference": "Reference date", "f.published": "Publication date",
    "f.retrieved": "Retrieval date", "f.frequency": "Update frequency", "f.state": "Source state",
    "f.cadence": "Observed cadence", "f.derivation": "Derivation", "f.route": "Retrieval route",
    "f.period": "Period semantics", "f.freshnessEvidence": "Date provenance",
    "f.ceiling": "Interpretation ceiling",
    "date.notPublished": "not published", "date.notRecorded": "not recorded in the registry (set at deployment)",
    "unit.residents": "registered residents", "unit.vutUnits": "licensed VUT units (administrative licence, not operating dwellings)",
    "unit.records": "register entries inside the circle", "unit.celsius": "°C UTCI (model-derived)",
    "unit.share": "share of register entries inside the circle", "unit.metres": "metres from the Lens centre",
    "unit.pedestrians": "observed pedestrians (not tourists)", "unit.hospitality": "as defined by the selected indicator",
    "unit.hotelDemand": "as defined by each hotel-occupancy indicator", "unit.tourists": "source-reported tourists",
    "derive.published": "Shown as published; no transformation by this product.",
    "derive.lensCount": "Count of source records whose point lies inside the Lens circle.",
    "derive.lensMean": "Descriptive statistic over source samples inside the Lens circle; no interpolation.",
    "derive.lensShare": "Share of the Lens-circle record counts by category.",
    "derive.nearest": "The nearest source records to the Lens centre, by straight-line distance.",
    "derive.compare": "Lens A and Lens B circle readings side by side; a difference is shown only when the two windows are comparable.",
    "derive.dynamics": "Presence and count change between two published months; a change in presence is not a change in tourists.",
    "surface.place.area.residents": "Registered residents",
    "surface.place.area.vut": "Licensed VUT units",
    "surface.place.metric.tourism": "Tourism POIs",
    "surface.place.metric.stays": "Hotels & stays",
    "surface.place.metric.mobility": "Mobility nodes",
    "surface.place.metric.utci": "Mean UTCI",
    "surface.place.detail.mix": "Category mix",
    "surface.place.detail.nearest": "Nearest in active lens",
    "surface.place.pedestrian": "Pedestrian flow",
    "surface.place.hospitality": "Hospitality & commercial context",
    "surface.layer.hati": "HATI study area",
    "surface.layer.pedestrian": "Pedestrian counters",
    "surface.compare.metric.tourism": "Lens A ↔ B · Tourism POIs",
    "surface.compare.metric.stays": "Lens A ↔ B · Hotels & stays",
    "surface.compare.metric.mobility": "Lens A ↔ B · Mobility nodes",
    "surface.compare.metric.utci": "Lens A ↔ B · Mean UTCI",
    "surface.compare.pedestrian": "Lens A ↔ B · Pedestrian flow",
    "surface.city.hotel_demand": "Hotel demand",
    "surface.city.domestic_origins": "Domestic origins",
    "surface.city.domestic_dynamics": "Monthly origin dynamics",
    "rail.unavailable": "unavailable", "date.loading": "—",
    "aside.map": "Map display", "aside.basemap": "Base map", "aside.boundaries": "Administrative boundaries",
    "aside.layers": "Operational layers", "aside.accommodation": "Accommodation category",
    "layer.museum": "Museums", "layer.stay": "Hotels & stays", "layer.info": "Tourist info", "layer.pedestrian": "Pedestrian counters",
    "layer.park": "Principal parks", "layer.hati": "HATI · thermal pilot",
    "aside.observed": "Observed activity", "aside.observedNote": "not tourism-specific",
    "aside.context": "Context", "aside.contextNote": "not in metrics",
    "aside.research": "Research evidence", "aside.researchNote": "bounded pilot",
    "hati.frame": "Show HATI pilot on the map",
    "hati.note": "<b>Evidence ceiling</b><br>HATI UTCI is <b>model-derived</b> (SOLWEIG), not measured comfort. Bounded to the locked 21 Aug 2023 Madrid pilot; no interpolation beyond the 14 sampled outdoor assets.<br><br>The dashed orange rectangle marks the original ≈3.5 km² HATI study-area boundary. It is <b>not</b> a continuous heat surface.",
    "brand.sub": "Madrid · Urban development · Official evidence",
    "sec.area": "Administrative area", "sec.circleOnly": "circle measurements only",
    "metric.tourism": "Tourism POIs", "metric.stays": "Hotels & stays", "metric.mobility": "Mobility nodes", "metric.utci": "Mean UTCI",
    "mix.title": "Category mix", "mix.nearest": "Nearest in active lens",
    "mix.museums": "Museums", "mix.stays": "Stays", "mix.mobility": "Mobility", "mix.info": "Info",
    "controls.reset": "Reset active lens", "controls.halo": "Comparison halo", "controls.haloNote": "supplementary map marks",
    "sources.body": "Sources: Ayuntamiento de Madrid — IDEAM (administrative geography: districts, barrios), Subdirección General de Estadística / Padrón Municipal (registered residents), and Censo de Locales (Hospitality & Commercial Context, Sep 2026 fingerprinted snapshot); Madrid Open Data (museums, tourist information, principal parks, permanent pedestrian counters); EMT Madrid (BiciMAD); CRTM (Metro and Cercanías stations); and Madrid Destino / esmadrid.com (hotels and other accommodation). The accommodation catalogue remains separate from the administrative Division-55 premises class. GitHub Pages uses the latest deployment-time POI snapshot first so markers render immediately; a small curated repository sample is the final packaged fallback when a deployment source is unavailable. HATI-Madrid locked pilot evidence (21 Aug 2023; UTCI is model output, not field observation). Destination context: Instituto Nacional de Estadística — hotel occupancy survey and direct internal-tourism municipality workbook (Madrid municipality only; domestic origin crossings published only above 30 tourists) — see <a href=\"docs/DATA_PROVENANCE.md\">data provenance</a> and <a href=\"docs/CLAIMS_AND_LIMITATIONS.md\">claims &amp; limitations</a>. Base maps: OpenStreetMap/CARTO or Esri World Imagery, depending on selection.",
    "legend.halo": "Fixed slots: Tourism POIs at 12 · Stays at 2 · Mobility nodes at 6 · Mean UTCI at 9 o’clock. Thin bars extend outward from each lens; the number is the raw value and length is density against a fixed Madrid reference (UTCI uses its model Celsius band). Lengths compare within the same metric only, never across metrics. Unavailable is N/A, never zero.",
  }),
  es: Object.freeze({
    "mode.place": "Lugar", "mode.compare": "Comparar", "mode.city": "Ciudad",
    "mode.q.place": "¿Qué dice la evidencia sobre este lugar?",
    "mode.q.compare": "¿Cómo se leen dos círculos de Lente uno frente al otro?",
    "mode.q.city": "¿Cuál es el contexto de todo el municipio?",
    "mode.announce": "Modo",
    "sec.detail": "Detalle", "sec.evidence": "Evidencia y límites", "sec.controls": "Controles",
    "sec.withinLens": "Dentro de la Lente", "sec.compare": "Lente A ↔ Lente B",
    "rail.reference": "Referencia", "rail.notPublished": "no publicada", "rail.state": "Estado",
    "rail.oldest": "Fecha de referencia más antigua entre las fuentes que contribuyen a lo que se ve en pantalla",
    "rail.open": "Abrir la evidencia de",
    "rail.lens": "Lente", "rail.locating": "localizando…", "rail.barrio": "barrio",
    "rail.multiple": "varios estados del editor",
    "scope.LENS_CIRCLE": "Círculo de Lente", "scope.OFFICIAL_BARRIO": "Barrio oficial",
    "scope.OFFICIAL_DISTRICT": "Distrito oficial", "scope.MUNICIPALITY": "Municipio",
    "scope.POINT_OBSERVATION": "Observación puntual", "scope.BOUNDED_STUDY_AREA": "Área de estudio",
    "scope.PLANNING_AMBITO": "Ámbito de planeamiento", "scope.EXECUTION_UNIT": "Unidad de ejecución",
    "scope.DEVELOPMENT_STAGE_AREA": "Área de etapa de desarrollo", "scope.PARCEL": "Parcela",
    "scope.ADDRESS_POINT": "Punto de dirección", "scope.WORK_GEOMETRY": "Geometría de obra",
    "scope.LENS_INTERSECT_AMBITO": "Lente ∩ ámbito",
    "state.DEFINITIVE": "Definitivo", "state.PROVISIONAL": "Provisional",
    "state.WITHHELD_BY_PUBLISHER": "Retenido por el editor",
    "state.NOT_DECLARED_BY_PUBLISHER": "No declarado por el editor",
    "freq.DAILY": "Diaria", "freq.WEEKLY": "Semanal", "freq.MONTHLY": "Mensual",
    "freq.BIMONTHLY": "Bimestral", "freq.QUARTERLY": "Trimestral", "freq.SEMESTRAL": "Semestral",
    "freq.ANNUAL": "Anual", "freq.IRREGULAR": "Irregular",
    "freq.DECLARED_UNDEFINED": "El editor la declara sin definir",
    "freq.NONE_DECLARED": "Sin frecuencia declarada",
    "drawer.title": "Evidencia y límites", "drawer.close": "Cerrar",
    "drawer.empty": "No hay registros de evidencia para esta selección.",
    "drawer.filter.all": "Toda la evidencia en pantalla en este modo",
    "drawer.filter.scope": "Filtrado por ámbito espacial",
    "drawer.notes.area": "Fuente e interpretación · Área administrativa",
    "drawer.notes.destination": "Fuente e interpretación · Contexto del destino",
    "drawer.legend": "Leyenda del halo de comparación", "drawer.sources": "Fuentes",
    "drawer.sourcesOf": "Fuente",
    "reading.label": "Lectura", "reading.citizen": "Ciudadana", "reading.analyst": "Analista",
    "f.source": "Fuente", "f.authority": "Autoridad", "f.scope": "Ámbito espacial", "f.scopeDefinition": "Definición del ámbito",
    "f.unit": "Unidad", "f.reference": "Fecha de referencia", "f.published": "Fecha de publicación",
    "f.retrieved": "Fecha de obtención", "f.frequency": "Frecuencia de actualización", "f.state": "Estado de la fuente",
    "f.cadence": "Cadencia observada", "f.derivation": "Derivación", "f.route": "Vía de obtención",
    "f.period": "Semántica del periodo", "f.freshnessEvidence": "Origen de las fechas",
    "f.ceiling": "Límite de interpretación",
    "date.notPublished": "no publicada", "date.notRecorded": "no registrada en el registro (se fija en el despliegue)",
    "unit.residents": "residentes empadronados", "unit.vutUnits": "unidades VUT con licencia (licencia administrativa, no viviendas en funcionamiento)",
    "unit.records": "registros de la fuente dentro del círculo", "unit.celsius": "°C UTCI (derivado de modelo)",
    "unit.share": "proporción de registros de la fuente dentro del círculo", "unit.metres": "metros desde el centro de la Lente",
    "unit.pedestrians": "peatones observados (no turistas)", "unit.hospitality": "según el indicador seleccionado",
    "unit.hotelDemand": "según cada indicador de ocupación hotelera", "unit.tourists": "turistas comunicados por la fuente",
    "derive.published": "Se muestra tal como se publica; este producto no la transforma.",
    "derive.lensCount": "Recuento de registros de la fuente cuyo punto cae dentro del círculo de la Lente.",
    "derive.lensMean": "Estadístico descriptivo de las muestras de la fuente dentro del círculo de la Lente; sin interpolación.",
    "derive.lensShare": "Proporción de los recuentos del círculo de la Lente por categoría.",
    "derive.nearest": "Los registros de la fuente más cercanos al centro de la Lente, por distancia en línea recta.",
    "derive.compare": "Lecturas de los círculos de la Lente A y la Lente B lado a lado; solo se muestra una diferencia cuando las dos ventanas son comparables.",
    "derive.dynamics": "Presencia y variación del recuento entre dos meses publicados; un cambio de presencia no es un cambio de turistas.",
    "surface.place.area.residents": "Residentes empadronados",
    "surface.place.area.vut": "Unidades VUT con licencia",
    "surface.place.metric.tourism": "POI turísticos",
    "surface.place.metric.stays": "Hoteles y alojamientos",
    "surface.place.metric.mobility": "Nodos de movilidad",
    "surface.place.metric.utci": "UTCI media",
    "surface.place.detail.mix": "Mezcla de categorías",
    "surface.place.detail.nearest": "Más cercanos en la Lente activa",
    "surface.place.pedestrian": "Flujo peatonal",
    "surface.place.hospitality": "Contexto de hostelería y actividad comercial",
    "surface.layer.hati": "Área de estudio HATI",
    "surface.layer.pedestrian": "Contadores de peatones",
    "surface.compare.metric.tourism": "Lente A ↔ B · POI turísticos",
    "surface.compare.metric.stays": "Lente A ↔ B · Hoteles y alojamientos",
    "surface.compare.metric.mobility": "Lente A ↔ B · Nodos de movilidad",
    "surface.compare.metric.utci": "Lente A ↔ B · UTCI media",
    "surface.compare.pedestrian": "Lente A ↔ B · Flujo peatonal",
    "surface.city.hotel_demand": "Demanda hotelera",
    "surface.city.domestic_origins": "Orígenes nacionales",
    "surface.city.domestic_dynamics": "Dinámica mensual de orígenes",
    "rail.unavailable": "no disponible", "date.loading": "—",
    "aside.map": "Visualización del mapa", "aside.basemap": "Mapa base", "aside.boundaries": "Límites administrativos",
    "aside.layers": "Capas operativas", "aside.accommodation": "Categoría de alojamiento",
    "layer.museum": "Museos", "layer.stay": "Hoteles y alojamientos", "layer.info": "Información turística", "layer.pedestrian": "Contadores de peatones",
    "layer.park": "Parques principales", "layer.hati": "HATI · piloto térmico",
    "aside.observed": "Actividad observada", "aside.observedNote": "no específica del turismo",
    "aside.context": "Contexto", "aside.contextNote": "fuera de las métricas",
    "aside.research": "Evidencia de investigación", "aside.researchNote": "piloto acotado",
    "hati.frame": "Mostrar el piloto HATI en el mapa",
    "hati.note": "<b>Límite de la evidencia</b><br>El UTCI de HATI es <b>derivado de un modelo</b> (SOLWEIG), no confort medido. Acotado al piloto de Madrid fijado el 21 ago 2023; sin interpolación más allá de los 14 elementos exteriores muestreados.<br><br>El rectángulo naranja discontinuo marca el límite original de ≈3,5 km² del área de estudio de HATI. <b>No</b> es una superficie de calor continua.",
    "brand.sub": "Madrid · Desarrollo urbano · Evidencia oficial",
    "sec.area": "Área administrativa", "sec.circleOnly": "solo mediciones del círculo",
    "metric.tourism": "POI turísticos", "metric.stays": "Hoteles y alojamientos", "metric.mobility": "Nodos de movilidad", "metric.utci": "UTCI media",
    "mix.title": "Mezcla de categorías", "mix.nearest": "Más cercanos en la Lente activa",
    "mix.museums": "Museos", "mix.stays": "Alojamientos", "mix.mobility": "Movilidad", "mix.info": "Información",
    "controls.reset": "Restablecer la Lente activa", "controls.halo": "Halo de comparación", "controls.haloNote": "marcas complementarias del mapa",
    "sources.body": "Fuentes: Ayuntamiento de Madrid — IDEAM (geografía administrativa: distritos, barrios), Subdirección General de Estadística / Padrón Municipal (residentes empadronados) y Censo de Locales (Contexto de hostelería y actividad comercial, instantánea con huella de sep. 2026); Madrid Open Data (museos, información turística, parques principales, contadores permanentes de peatones); EMT Madrid (BiciMAD); CRTM (estaciones de Metro y Cercanías); y Madrid Destino / esmadrid.com (hoteles y otros alojamientos). El catálogo de alojamientos sigue separado de la clase administrativa de locales de la División 55. GitHub Pages usa primero la instantánea de POI más reciente del despliegue para que los marcadores se pinten de inmediato; una pequeña muestra curada del repositorio es el último recurso empaquetado cuando una fuente del despliegue no está disponible. Evidencia fijada del piloto HATI-Madrid (21 ago 2023; el UTCI es salida de modelo, no observación de campo). Contexto del destino: Instituto Nacional de Estadística — encuesta de ocupación hotelera y libro de turismo interno por municipio (solo el municipio de Madrid; los cruces de origen nacional se publican solo por encima de 30 turistas) — véanse la <a href=\"docs/DATA_PROVENANCE.md\">procedencia de los datos</a> y las <a href=\"docs/CLAIMS_AND_LIMITATIONS.md\">afirmaciones y limitaciones</a>. Mapas base: OpenStreetMap/CARTO o Esri World Imagery, según la selección.",
    "legend.halo": "Posiciones fijas: POI turísticos a las 12 · Alojamientos a las 2 · Nodos de movilidad a las 6 · UTCI media a las 9. Las barras finas salen hacia fuera de cada Lente; el número es el valor bruto y la longitud es la densidad frente a una referencia fija de Madrid (el UTCI usa su banda de grados Celsius del modelo). Las longitudes solo se comparan dentro de la misma métrica, nunca entre métricas. No disponible es N/D, nunca cero.",
  }),
});

if (typeof module !== "undefined" && module.exports) {
  module.exports = { SHELL_DICTIONARIES };
}
