// Shell copy — the ES/EN dictionaries for the K4 information architecture.
//
// ONE document language at a time. These dictionaries cover the surfaces K4 owns
// (mode control, scope & freshness rail, evidence drawer, section structure,
// layer-scoped controls and the static panel labels it re-homed). They are loaded
// through the shared createI18n mechanism in js/i18n.js, exactly like the Bridge,
// hospitality and origin dictionaries, so there is one language-selection and
// fallback path and no render function holds a literal string for a new surface.
//
// Official source VALUES are never translated here: an interpretation ceiling or
// a publisher's own wording is carried verbatim from data/source_registry.json.
// Only our labels around them change language.

const SHELL_DICTIONARIES = Object.freeze({
  en: Object.freeze({
    "mode.place": "Place", "mode.compare": "Compare", "mode.city": "City",
    "mode.q.place": "What does the evidence say about this place?",
    "mode.q.compare": "How do two Lens circles read against each other?",
    "mode.q.city": "What is the municipality-wide context?",
    "mode.announce": "Mode",
    "sec.detail": "Detail", "sec.evidence": "Evidence & limits", "sec.controls": "Controls",
    "sec.withinLens": "Within the Lens", "sec.compare": "Lens A ↔ Lens B",
    "rail.reference": "Reference", "rail.notPublished": "not published", "rail.state": "State",
    "rail.oldest": "Oldest reference date among the sources contributing to what is on screen",
    "rail.open": "Open the evidence for",
    "rail.lens": "Lens", "rail.locating": "locating…", "rail.barrio": "barrio",
    "rail.multiple": "several publisher states",
    "scope.LENS_CIRCLE": "Lens circle", "scope.OFFICIAL_BARRIO": "Official barrio",
    "scope.OFFICIAL_DISTRICT": "Official district", "scope.MUNICIPALITY": "Municipality",
    "scope.POINT_OBSERVATION": "Point observation", "scope.BOUNDED_STUDY_AREA": "Study area",
    "scope.PLANNING_AMBITO": "Planning ámbito", "scope.EXECUTION_UNIT": "Execution unit",
    "scope.DEVELOPMENT_STAGE_AREA": "Development stage area", "scope.PARCEL": "Parcel",
    "scope.ADDRESS_POINT": "Address point", "scope.WORK_GEOMETRY": "Work geometry",
    "scope.LENS_INTERSECT_AMBITO": "Lens ∩ ámbito",
    "state.DEFINITIVE": "Definitive", "state.PROVISIONAL": "Provisional",
    "state.WITHHELD_BY_PUBLISHER": "Withheld by publisher",
    "state.NOT_DECLARED_BY_PUBLISHER": "Not declared by publisher",
    "freq.DAILY": "Daily", "freq.WEEKLY": "Weekly", "freq.MONTHLY": "Monthly",
    "freq.BIMONTHLY": "Bimonthly", "freq.QUARTERLY": "Quarterly", "freq.SEMESTRAL": "Semestral",
    "freq.ANNUAL": "Annual", "freq.IRREGULAR": "Irregular",
    "freq.DECLARED_UNDEFINED": "Publisher declares it undefined",
    "freq.NONE_DECLARED": "No frequency declared",
    "drawer.title": "Evidence & limits", "drawer.close": "Close",
    "drawer.empty": "No evidence records for this selection.",
    "drawer.filter.all": "All evidence on screen in this mode",
    "drawer.filter.scope": "Filtered to scope",
    "drawer.notes.area": "Source & interpretation · Administrative area",
    "drawer.notes.destination": "Source & interpretation · Destination context",
    "drawer.legend": "Comparison halo legend", "drawer.sources": "Sources",
    "drawer.sourcesOf": "Source",
    "reading.label": "Reading", "reading.citizen": "Citizen", "reading.analyst": "Analyst",
    "f.source": "Source", "f.authority": "Authority", "f.scope": "Scope", "f.scopeDefinition": "Scope definition",
    "f.unit": "Unit", "f.reference": "Reference date", "f.published": "Publication date",
    "f.retrieved": "Retrieval date", "f.frequency": "Update frequency", "f.state": "Source state",
    "f.cadence": "Observed cadence", "f.derivation": "Derivation", "f.route": "Retrieval route",
    "f.period": "Period semantics", "f.freshnessEvidence": "Date provenance",
    "f.ceiling": "Interpretation ceiling",
    "date.notPublished": "not published", "date.notRecorded": "not recorded in the registry (set at deployment)",
    "unit.residents": "registered residents", "unit.vutUnits": "licensed VUT units (administrative licence, not operating dwellings)",
    "unit.records": "register entries inside the circle", "unit.celsius": "°C UTCI (model-derived)",
    "unit.share": "share of register entries inside the circle", "unit.metres": "metres from the Lens centre",
    "unit.pedestrians": "observed pedestrians (not tourists)", "unit.hospitality": "as defined by the selected indicator",
    "unit.hotelDemand": "as defined by each hotel-occupancy indicator", "unit.tourists": "source-reported tourists",
    "derive.published": "Shown as published; no transformation by this product.",
    "derive.lensCount": "Count of source records whose point lies inside the Lens circle.",
    "derive.lensMean": "Descriptive statistic over source samples inside the Lens circle; no interpolation.",
    "derive.lensShare": "Share of the Lens-circle record counts by category.",
    "derive.nearest": "The nearest source records to the Lens centre, by straight-line distance.",
    "derive.compare": "Lens A and Lens B circle readings side by side; a difference is shown only when the two windows are comparable.",
    "derive.dynamics": "Presence and count change between two published months; a change in presence is not a change in tourists.",
    "derive.ambitoContainment": "Which official planning ámbito contains the Lens centre, by point-in-polygon against the committed official geometry.",
    "derive.ambitoMembership": "Which official planning ámbitos the Lens circle touches. Membership only: no share, proportion or part of any ámbito's published quantities is computed.",
    "unit.ambitoIdentity": "official ámbito code and denomination",
    "unit.phaseState": "published administrative phase value (verbatim)",
    "unit.squareMetres": "m² (published ámbito surface)",
    "unit.buildability": "m² edificable (available planning buildability, whole ámbito)",
    "unit.ambitoChange": "published evidence from two official editions",
    "unit.touchedAmbitos": "ámbitos touched by the Lens circle (a count of areas, not a share of their quantities)",
    "surface.place.planning.ambito": "Planning ámbito",
    "surface.place.planning.phases": "Published development phases",
    "surface.place.planning.surface": "Ámbito surface",
    "surface.place.planning.buildability": "Available buildability",
    "surface.place.planning.touched": "Planning ámbitos touched by the Lens",
    "surface.place.area.residents": "Registered residents",
    "surface.place.area.vut": "Licensed VUT units",
    "surface.place.metric.tourism": "Tourism POIs",
    "surface.place.metric.stays": "Hotels & stays",
    "surface.place.metric.mobility": "Mobility nodes",
    "surface.place.metric.utci": "Mean UTCI",
    "surface.place.detail.mix": "Category mix",
    "surface.place.detail.nearest": "Nearest in active lens",
    "surface.place.pedestrian": "Pedestrian flow",
    "surface.place.hospitality": "Hospitality & commercial context",
    "surface.layer.hati": "HATI study area",
    "surface.layer.pedestrian": "Pedestrian counters",
    "surface.compare.metric.tourism": "Lens A ↔ B · Tourism POIs",
    "surface.compare.metric.stays": "Lens A ↔ B · Hotels & stays",
    "surface.compare.metric.mobility": "Lens A ↔ B · Mobility nodes",
    "surface.compare.metric.utci": "Lens A ↔ B · Mean UTCI",
    "surface.compare.pedestrian": "Lens A ↔ B · Pedestrian flow",
    "surface.city.hotel_demand": "Hotel demand",
    "surface.city.domestic_origins": "Domestic origins",
    "surface.city.domestic_dynamics": "Monthly origin dynamics",
    "rail.unavailable": "unavailable", "date.loading": "—",
    "aside.map": "Map display", "aside.basemap": "Base map", "aside.boundaries": "Administrative boundaries",
    "aside.layers": "Operational layers", "aside.accommodation": "Accommodation category",
    "layer.museum": "Museums", "layer.stay": "Hotels & stays", "layer.info": "Tourist info", "layer.pedestrian": "Pedestrian counters",
    "layer.park": "Principal parks", "layer.hati": "HATI · thermal pilot",
    "aside.observed": "Observed activity", "aside.observedNote": "not tourism-specific",
    "aside.context": "Context", "aside.contextNote": "not in metrics",
    "aside.research": "Research evidence", "aside.researchNote": "bounded pilot",
    "hati.frame": "Show HATI pilot on the map",
    "hati.note": "<b>Evidence ceiling</b><br>HATI UTCI is <b>model-derived</b> (SOLWEIG), not measured comfort. Bounded to the locked 21 Aug 2023 Madrid pilot; no interpolation beyond the 14 sampled outdoor assets.<br><br>The dashed orange rectangle marks the original ≈3.5 km² HATI study-area boundary. It is <b>not</b> a continuous heat surface.",
    "brand.sub": "Madrid · Urban development · Official evidence",
    "sec.area": "Administrative area", "sec.circleOnly": "circle measurements only",
    // ---- K6 planning-ámbito evidence (#68). Product-authored copy only: every
    // official value (ámbito code, denomination, phase value, situación) is
    // rendered verbatim under data-verbatim and is never translated here.
    "sec.planning": "Planning ámbito", "planning.scopeHint": "whole planning ámbito",
    "planning.kind": "Planning ámbito",
    "planning.codeLabel": "Official code",
    "planning.distinction": "An official planning area. It is not the barrio, not the district and not the Lens circle.",
    "planning.loading": "Locating…",
    "planning.unavailable": "Planning evidence is unavailable in this deployment.",
    "planning.outside": "No official planning ámbito contains the Lens centre. The ámbito universe does not cover the whole municipality, so this is an explicit absence of a containing ámbito — not a zero and not the nearest ámbito.",
    "planning.editionLabel": "Published state at",
    "planning.editionSuffix": "official edition",
    "planning.phasesTitle": "Four published development phases",
    "planning.phasesNote": "Four independent published fields. The publisher documents no order between them, so they do not form one overall stage and no progress, percentage, completion or timeline figure is derived.",
    "planning.phase.planeamiento": "Planeamiento (planning instrument)",
    "planning.phase.gestion": "Gestión (land management)",
    "planning.phase.urbanizacion_proyecto": "Urbanización · Proyecto (works design)",
    "planning.phase.urbanizacion_obras": "Urbanización · Obras (works)",
    "planning.note.unresolved": "The publisher lists this as a distinct state; its precise meaning is not defined in the audited documentation.",
    "planning.note.marker": "A plan-of-origin marker published in this phase column, not a development state.",
    "planning.note.undocumented": "Observed in the published data; not listed in the publisher's structure document.",
    "planning.glyph.unresolved": "Unresolved meaning",
    "planning.glyph.marker": "Plan-of-origin marker",
    "planning.useLabel": "Characteristic use",
    "planning.surfaceLabel": "Ámbito surface",
    "planning.districtLabel": "District in the edition",
    "planning.buildTitle": "Available buildability · edificabilidad disponible",
    "planning.buildScope": "Whole planning ámbito — not the Lens circle.",
    "planning.buildNote": "What the plan makes available, by use class. Not what remains to be physically built, and not an estimate of what will be built.",
    "planning.use.colectiva_residencial": "Collective residential",
    "planning.use.unifamiliar_residencial": "Single-family residential",
    "planning.use.industrial": "Industrial",
    "planning.use.terciario": "Tertiary",
    "planning.notPublished": "not published",
    "planning.rounding": "Displayed figures are rounded; each published value is carried in full under Evidence & limits.",
    "planning.multipleRows": "The selected edition publishes more than one row for this ámbito. The rows are shown separately and are never added together.",
    "planning.situacionLabel": "Published situación",
    "planning.stateNotPublished": "The selected official edition publishes no development-state row for this ámbito.",
    "planning.buildNotPublished": "The selected official edition publishes no available-buildability row for this ámbito.",
    "planning.absenceNote": "An absence of published evidence, not a zero.",
    "planning.touchedTitle": "Planning ámbitos touched by the Lens",
    "planning.touchedNote": "Which ámbitos the Lens circle touches. No share, proportion or part of their published quantities is computed or implied.",
    "planning.touchedNone": "The Lens circle touches no official planning ámbito.",
    "planning.touchedCentre": "contains the Lens centre",
    "planning.citizen.title": "What this means",
    "planning.citizen.what": "This place sits inside an official planning ámbito — the area in which Madrid's general plan records development state and available buildability.",
    "planning.citizen.states": "The plan publishes four separate development values for it, shown below exactly as published.",
    "planning.citizen.build": "It also publishes how much buildability the plan makes available there, by use class, in m² edificable.",
    "planning.citizen.date": "All of it comes from one dated official edition, whose reference date is shown with the figures.",
    "planning.citizen.cannot": "What it does not say: nothing here measures physical construction, the four values do not combine into one stage or percentage, no number of homes is published or derivable, and no figure is a share of the Lens circle.",
    "planning.ceiling": "Four independent published administrative phase values and available planning buildability in m² edificable, from one dated official edition, for the whole ámbito. A published phase state is an administrative state, never proof of physical construction. No overall stage, progress, percentage or timeline exists. No dwelling count is published or derivable. No figure is apportioned into the Lens circle, the barrio or any sub-area.",
    "planning.source": "Source & interpretation",
    "planning.change.title": "Official edition comparison",
    "planning.change.intro": "Published evidence for this ámbito in two named official editions.",
    "planning.change.previous": "Previous edition",
    "planning.change.current": "Current edition",
    "planning.change.datesAria": "Compared official edition dates",
    "planning.change.scope": "A difference in a publication describes published planning evidence; it does not establish physical urban change or its cause.",
    "planning.change.analyst": "Analyst reading",
    "planning.change.noChange": "No substantive published difference detected between {previous} and {current}.",
    "planning.change.state": "Published state changed",
    "planning.change.new": "New in this edition",
    "planning.change.absent": "Absent from this edition",
    "planning.change.absenceCauseUnknown": "Cause unresolved. The official material does not give a reason for this exact code.",
    "planning.change.instrument": "Modified by planning instrument",
    "planning.change.unresolved": "Cause unresolved",
    "planning.change.nonComparable": "Not comparable",
    "planning.change.outcome.s1": "Four published phase fields",
    "planning.change.outcome.s2": "Published situation and notes",
    "planning.change.previousValue": "Previous published value",
    "planning.change.currentValue": "Current published value",
    "planning.change.instrumentRef": "Planning instrument",
    "planning.change.caveat": "Comparison may not be like-for-like across this instrument modification.",
    "planning.change.numericTitle": "Available buildability comparison",
    "planning.change.observed": "Observed published difference",
    "planning.change.numericNoChange": "No substantive published difference detected between {previous} and {current}.",
    "planning.change.withheld": "Numeric comparison withheld",
    "planning.change.situation": "Published situación",
    "planning.change.reason": "Reason",
    "planning.change.reasonUnknown": "The publications do not state a reason.",
    "planning.change.reason.pairRecords": "Both named edition records are required.",
    "planning.change.reason.familyMismatch": "The editions do not identify the same source family.",
    "planning.change.reason.datesMissing": "Both source-stated reference dates are required.",
    "planning.change.reason.datesOrder": "The named editions must have distinct, ordered reference dates.",
    "planning.change.reason.identityMissing": "Both edition identities and full fingerprints are required.",
    "planning.change.reason.sameEdition": "The same edition cannot be supplied twice.",
    "planning.change.reason.eraMismatch": "The editions belong to different or unspecified schema eras.",
    "planning.change.reason.recordsMissing": "Both edition record sets are required.",
    "planning.change.reason.duplicateSituations": "Duplicate situation labels prevent a defensible one-to-one row correspondence.",
    "planning.change.reason.rowSituationMissing": "A published row has no usable SITUACION DEL ÁMBITO identity.",
    "planning.change.reason.rowUnmatched": "One or more published rows have no counterpart in the other edition.",
    "planning.change.reason.instrumentDocumented": "A dated, applicable planning instrument event is documented for a compared field.",
    "planning.change.reason.scopedCodeRequired": "An exact edition-scoped ámbito code is required.",
    "planning.change.reason.noRecordsForCode": "Neither named edition publishes a record for this exact code.",
    "planning.change.reason.codeAppearsLater": "The exact code is present in the later named edition and absent from the earlier named edition.",
    "planning.change.reason.codeAbsentLater": "The exact code is present in the earlier named edition and absent from the later named edition.",
    "planning.change.reason.phaseFieldsMissing": "A phase record does not carry the four required published fields.",
    "planning.change.reason.rowSetMalformed": "A published row set is malformed and cannot be classified.",
    "planning.change.reason.noClassifierContract": "The source family has no K7 classifier contract.",
    "planning.change.reason.phaseValuesDiffer": "One or more published S1 phase values differ between the editions.",
    "planning.change.reason.situationDiffers": "The sole published S2 situation value differs between the editions.",
    "planning.change.reason.s2Counterpart": "One or more published S2 rows has no defensible counterpart; the editions do not establish a planning event.",
    "planning.change.reason.noteCauseUnknown": "A substantive published note differs and the editions do not establish why.",
    "planning.change.reason.noSubstantiveDifference": "No substantive difference was detected in the fields with a defensible comparison.",
    "planning.change.reason.codeRequired": "An exact edition-scoped code is required.",
    "planning.change.reason.laterOnly": "Absent from the earlier edition and present in the later edition.",
    "planning.change.reason.earlierOnly": "Present in the earlier edition and absent from the later edition.",
    "planning.change.reason.numericDuplicate": "Duplicate situation labels prevent a defensible numeric row match.",
    "planning.change.reason.numericSituationMissing": "A row lacks a usable published situation identity.",
    "planning.change.reason.numericUnmatched": "One or more rows has no one-to-one counterpart; numeric comparison is withheld for those rows.",
    "planning.change.reason.pairNotComparable": "The edition pair is not comparable.",
    "planning.change.reason.buildabilityRowsMissing": "Both named editions must publish S2 rows for this exact code.",
    "planning.change.reason.numericValuesRequired": "Both editions must publish numeric values for the same documented use class; blank is not zero.",
    "planning.change.reason.unmatchedRow": "This published row has no defensible counterpart in the other edition.",
    "planning.change.reason.someNumericWithheld": "At least one numeric comparison is withheld.",
    "planning.change.reason.instrumentNumeric": "Withheld across {reference}; the published values may not be like-for-like.",
    "planning.change.matchingBasis": "Exact code plus a unique, stable SITUACION DEL ÁMBITO value within each edition.",
    "planning.change.rowBasis": "Row matching basis",
    "planning.change.provenance": "Compared edition provenance",
    "planning.change.resource": "Resource identity",
    "planning.change.fingerprint": "SHA-256 fingerprint",
    "planning.change.schemaEra": "Schema era",
    "planning.change.source": "Source record",
    "planning.change.retrieved": "Retrieved",
    "planning.change.previousEdition": "Previous",
    "planning.change.currentEdition": "Current",
    "surface.place.planning.change": "Official edition comparison",
    "month.1": "Jan", "month.2": "Feb", "month.3": "Mar", "month.4": "Apr",
    "month.5": "May", "month.6": "Jun", "month.7": "Jul", "month.8": "Aug",
    "month.9": "Sep", "month.10": "Oct", "month.11": "Nov", "month.12": "Dec",
    "metric.tourism": "Tourism POIs", "metric.stays": "Hotels & stays", "metric.mobility": "Mobility nodes", "metric.utci": "Mean UTCI",
    "mix.title": "Category mix", "mix.nearest": "Nearest in active lens",
    "mix.museums": "Museums", "mix.stays": "Stays", "mix.mobility": "Mobility", "mix.info": "Info",
    "controls.reset": "Reset active lens", "controls.halo": "Comparison halo", "controls.haloNote": "supplementary map marks",
    "sources.body": "Sources: Ayuntamiento de Madrid — IDEAM (administrative geography: districts, barrios), Subdirección General de Estadística / Padrón Municipal (registered residents), and Censo de Locales (Hospitality & Commercial Context, Sep 2026 fingerprinted snapshot); Madrid Open Data (museums, tourist information, principal parks, permanent pedestrian counters); EMT Madrid (BiciMAD); CRTM (Metro and Cercanías stations); and Madrid Destino / esmadrid.com (hotels and other accommodation). The accommodation catalogue remains separate from the administrative Division-55 premises class. GitHub Pages uses the latest deployment-time POI snapshot first so markers render immediately; a small curated repository sample is the final packaged fallback when a deployment source is unavailable. HATI-Madrid locked pilot evidence (21 Aug 2023; UTCI is model output, not field observation). Destination context: Instituto Nacional de Estadística — hotel occupancy survey and direct internal-tourism municipality workbook (Madrid municipality only; domestic origin crossings published only above 30 tourists) — see <a href=\"docs/DATA_PROVENANCE.md\">data provenance</a> and <a href=\"docs/CLAIMS_AND_LIMITATIONS.md\">claims &amp; limitations</a>. Base maps: OpenStreetMap/CARTO or Esri World Imagery, depending on selection.",
    "legend.halo": "Fixed slots: Tourism POIs at 12 · Stays at 2 · Mobility nodes at 6 · Mean UTCI at 9 o’clock. Thin bars extend outward from each lens; the number is the raw value and length is density against a fixed Madrid reference (UTCI uses its model Celsius band). Lengths compare within the same metric only, never across metrics. Unavailable is N/A, never zero.",
  }),
  es: Object.freeze({
    "mode.place": "Lugar", "mode.compare": "Comparar", "mode.city": "Ciudad",
    "mode.q.place": "¿Qué dice la evidencia sobre este lugar?",
    "mode.q.compare": "¿Cómo se leen dos círculos de Lente uno frente al otro?",
    "mode.q.city": "¿Cuál es el contexto de todo el municipio?",
    "mode.announce": "Modo",
    "sec.detail": "Detalle", "sec.evidence": "Evidencia y límites", "sec.controls": "Controles",
    "sec.withinLens": "Dentro de la Lente", "sec.compare": "Lente A ↔ Lente B",
    "rail.reference": "Referencia", "rail.notPublished": "no publicada", "rail.state": "Estado",
    "rail.oldest": "Fecha de referencia más antigua entre las fuentes que contribuyen a lo que se ve en pantalla",
    "rail.open": "Abrir la evidencia de",
    "rail.lens": "Lente", "rail.locating": "localizando…", "rail.barrio": "barrio",
    "rail.multiple": "varios estados del editor",
    "scope.LENS_CIRCLE": "Círculo de Lente", "scope.OFFICIAL_BARRIO": "Barrio oficial",
    "scope.OFFICIAL_DISTRICT": "Distrito oficial", "scope.MUNICIPALITY": "Municipio",
    "scope.POINT_OBSERVATION": "Observación puntual", "scope.BOUNDED_STUDY_AREA": "Área de estudio",
    "scope.PLANNING_AMBITO": "Ámbito de planeamiento", "scope.EXECUTION_UNIT": "Unidad de ejecución",
    "scope.DEVELOPMENT_STAGE_AREA": "Área de etapa de desarrollo", "scope.PARCEL": "Parcela",
    "scope.ADDRESS_POINT": "Punto de dirección", "scope.WORK_GEOMETRY": "Geometría de obra",
    "scope.LENS_INTERSECT_AMBITO": "Lente ∩ ámbito",
    "state.DEFINITIVE": "Definitivo", "state.PROVISIONAL": "Provisional",
    "state.WITHHELD_BY_PUBLISHER": "Retenido por el editor",
    "state.NOT_DECLARED_BY_PUBLISHER": "No declarado por el editor",
    "freq.DAILY": "Diaria", "freq.WEEKLY": "Semanal", "freq.MONTHLY": "Mensual",
    "freq.BIMONTHLY": "Bimestral", "freq.QUARTERLY": "Trimestral", "freq.SEMESTRAL": "Semestral",
    "freq.ANNUAL": "Anual", "freq.IRREGULAR": "Irregular",
    "freq.DECLARED_UNDEFINED": "El editor la declara sin definir",
    "freq.NONE_DECLARED": "Sin frecuencia declarada",
    "drawer.title": "Evidencia y límites", "drawer.close": "Cerrar",
    "drawer.empty": "No hay registros de evidencia para esta selección.",
    "drawer.filter.all": "Toda la evidencia en pantalla en este modo",
    "drawer.filter.scope": "Filtrado por ámbito espacial",
    "drawer.notes.area": "Fuente e interpretación · Área administrativa",
    "drawer.notes.destination": "Fuente e interpretación · Contexto del destino",
    "drawer.legend": "Leyenda del halo de comparación", "drawer.sources": "Fuentes",
    "drawer.sourcesOf": "Fuente",
    "reading.label": "Lectura", "reading.citizen": "Ciudadana", "reading.analyst": "Analista",
    "f.source": "Fuente", "f.authority": "Autoridad", "f.scope": "Ámbito espacial", "f.scopeDefinition": "Definición del ámbito",
    "f.unit": "Unidad", "f.reference": "Fecha de referencia", "f.published": "Fecha de publicación",
    "f.retrieved": "Fecha de obtención", "f.frequency": "Frecuencia de actualización", "f.state": "Estado de la fuente",
    "f.cadence": "Cadencia observada", "f.derivation": "Derivación", "f.route": "Vía de obtención",
    "f.period": "Semántica del periodo", "f.freshnessEvidence": "Origen de las fechas",
    "f.ceiling": "Límite de interpretación",
    "date.notPublished": "no publicada", "date.notRecorded": "no registrada en el registro (se fija en el despliegue)",
    "unit.residents": "residentes empadronados", "unit.vutUnits": "unidades VUT con licencia (licencia administrativa, no viviendas en funcionamiento)",
    "unit.records": "registros de la fuente dentro del círculo", "unit.celsius": "°C UTCI (derivado de modelo)",
    "unit.share": "proporción de registros de la fuente dentro del círculo", "unit.metres": "metros desde el centro de la Lente",
    "unit.pedestrians": "peatones observados (no turistas)", "unit.hospitality": "según el indicador seleccionado",
    "unit.hotelDemand": "según cada indicador de ocupación hotelera", "unit.tourists": "turistas comunicados por la fuente",
    "derive.published": "Se muestra tal como se publica; este producto no la transforma.",
    "derive.lensCount": "Recuento de registros de la fuente cuyo punto cae dentro del círculo de la Lente.",
    "derive.lensMean": "Estadístico descriptivo de las muestras de la fuente dentro del círculo de la Lente; sin interpolación.",
    "derive.lensShare": "Proporción de los recuentos del círculo de la Lente por categoría.",
    "derive.nearest": "Los registros de la fuente más cercanos al centro de la Lente, por distancia en línea recta.",
    "derive.compare": "Lecturas de los círculos de la Lente A y la Lente B lado a lado; solo se muestra una diferencia cuando las dos ventanas son comparables.",
    "derive.dynamics": "Presencia y variación del recuento entre dos meses publicados; un cambio de presencia no es un cambio de turistas.",
    "derive.ambitoContainment": "Qué ámbito oficial de planeamiento contiene el centro de la Lente, por punto en polígono contra la geometría oficial incorporada.",
    "derive.ambitoMembership": "Qué ámbitos oficiales de planeamiento toca el círculo de Lente. Solo pertenencia: no se calcula ninguna parte, proporción ni porción de las cantidades publicadas de ningún ámbito.",
    "unit.ambitoIdentity": "código y denominación oficiales del ámbito",
    "unit.phaseState": "valor de fase administrativo publicado (literal)",
    "unit.squareMetres": "m² (superficie publicada del ámbito)",
    "unit.buildability": "m² edificable (edificabilidad disponible de planeamiento, ámbito completo)",
    "unit.ambitoChange": "evidencia publicada de dos ediciones oficiales",
    "unit.touchedAmbitos": "ámbitos que toca el círculo de Lente (un recuento de áreas, no una parte de sus cantidades)",
    "surface.place.planning.ambito": "Ámbito de planeamiento",
    "surface.place.planning.phases": "Fases de desarrollo publicadas",
    "surface.place.planning.surface": "Superficie del ámbito",
    "surface.place.planning.buildability": "Edificabilidad disponible",
    "surface.place.planning.touched": "Ámbitos de planeamiento que toca la Lente",
    "surface.place.area.residents": "Residentes empadronados",
    "surface.place.area.vut": "Unidades VUT con licencia",
    "surface.place.metric.tourism": "POI turísticos",
    "surface.place.metric.stays": "Hoteles y alojamientos",
    "surface.place.metric.mobility": "Nodos de movilidad",
    "surface.place.metric.utci": "UTCI media",
    "surface.place.detail.mix": "Mezcla de categorías",
    "surface.place.detail.nearest": "Más cercanos en la Lente activa",
    "surface.place.pedestrian": "Flujo peatonal",
    "surface.place.hospitality": "Contexto de hostelería y actividad comercial",
    "surface.layer.hati": "Área de estudio HATI",
    "surface.layer.pedestrian": "Contadores de peatones",
    "surface.compare.metric.tourism": "Lente A ↔ B · POI turísticos",
    "surface.compare.metric.stays": "Lente A ↔ B · Hoteles y alojamientos",
    "surface.compare.metric.mobility": "Lente A ↔ B · Nodos de movilidad",
    "surface.compare.metric.utci": "Lente A ↔ B · UTCI media",
    "surface.compare.pedestrian": "Lente A ↔ B · Flujo peatonal",
    "surface.city.hotel_demand": "Demanda hotelera",
    "surface.city.domestic_origins": "Orígenes nacionales",
    "surface.city.domestic_dynamics": "Dinámica mensual de orígenes",
    "rail.unavailable": "no disponible", "date.loading": "—",
    "aside.map": "Visualización del mapa", "aside.basemap": "Mapa base", "aside.boundaries": "Límites administrativos",
    "aside.layers": "Capas operativas", "aside.accommodation": "Categoría de alojamiento",
    "layer.museum": "Museos", "layer.stay": "Hoteles y alojamientos", "layer.info": "Información turística", "layer.pedestrian": "Contadores de peatones",
    "layer.park": "Parques principales", "layer.hati": "HATI · piloto térmico",
    "aside.observed": "Actividad observada", "aside.observedNote": "no específica del turismo",
    "aside.context": "Contexto", "aside.contextNote": "fuera de las métricas",
    "aside.research": "Evidencia de investigación", "aside.researchNote": "piloto acotado",
    "hati.frame": "Mostrar el piloto HATI en el mapa",
    "hati.note": "<b>Límite de la evidencia</b><br>El UTCI de HATI es <b>derivado de un modelo</b> (SOLWEIG), no confort medido. Acotado al piloto de Madrid fijado el 21 ago 2023; sin interpolación más allá de los 14 elementos exteriores muestreados.<br><br>El rectángulo naranja discontinuo marca el límite original de ≈3,5 km² del área de estudio de HATI. <b>No</b> es una superficie de calor continua.",
    "brand.sub": "Madrid · Desarrollo urbano · Evidencia oficial",
    "sec.area": "Área administrativa", "sec.circleOnly": "solo mediciones del círculo",
    // ---- K6 (#68). Copia redactada por el producto. Los valores oficiales
    // (código de ámbito, denominación, valor de fase, situación) se muestran
    // literalmente bajo data-verbatim y nunca se traducen aquí.
    "sec.planning": "Ámbito de planeamiento", "planning.scopeHint": "ámbito de planeamiento completo",
    "planning.kind": "Ámbito de planeamiento",
    "planning.codeLabel": "Código oficial",
    "planning.distinction": "Un área oficial de planeamiento. No es el barrio, no es el distrito y no es el círculo de Lente.",
    "planning.loading": "Localizando…",
    "planning.unavailable": "La evidencia de planeamiento no está disponible en este despliegue.",
    "planning.outside": "Ningún ámbito oficial de planeamiento contiene el centro de la Lente. El universo de ámbitos no cubre todo el municipio, así que esto es una ausencia explícita de ámbito contenedor: no es un cero ni es el ámbito más cercano.",
    "planning.editionLabel": "Estado publicado a fecha de",
    "planning.editionSuffix": "edición oficial",
    "planning.phasesTitle": "Cuatro fases de desarrollo publicadas",
    "planning.phasesNote": "Cuatro campos publicados independientes. El editor no documenta ningún orden entre ellos, por lo que no forman una etapa global y no se deriva ninguna cifra de avance, porcentaje, finalización ni calendario.",
    "planning.phase.planeamiento": "Planeamiento (instrumento de planeamiento)",
    "planning.phase.gestion": "Gestión (gestión del suelo)",
    "planning.phase.urbanizacion_proyecto": "Urbanización · Proyecto (proyecto de obras)",
    "planning.phase.urbanizacion_obras": "Urbanización · Obras (obras)",
    "planning.note.unresolved": "El editor lo recoge como un estado distinto; su significado preciso no está definido en la documentación auditada.",
    "planning.note.marker": "Un marcador de plan de origen publicado en esta columna de fase, no un estado de desarrollo.",
    "planning.note.undocumented": "Observado en los datos publicados; no figura en el documento de estructura del editor.",
    "planning.glyph.unresolved": "Significado no resuelto",
    "planning.glyph.marker": "Marcador de plan de origen",
    "planning.useLabel": "Uso característico",
    "planning.surfaceLabel": "Superficie del ámbito",
    "planning.districtLabel": "Distrito en la edición",
    "planning.buildTitle": "Edificabilidad disponible",
    "planning.buildScope": "Ámbito de planeamiento completo — no el círculo de Lente.",
    "planning.buildNote": "Lo que el plan deja disponible, por clase de uso. No es lo que queda por construir físicamente ni una estimación de lo que se construirá.",
    "planning.use.colectiva_residencial": "Residencial colectiva",
    "planning.use.unifamiliar_residencial": "Residencial unifamiliar",
    "planning.use.industrial": "Industrial",
    "planning.use.terciario": "Terciario",
    "planning.notPublished": "no publicado",
    "planning.rounding": "Las cifras mostradas están redondeadas; cada valor publicado se recoge íntegro en Evidencia y límites.",
    "planning.multipleRows": "La edición seleccionada publica más de una fila para este ámbito. Las filas se muestran por separado y nunca se suman.",
    "planning.situacionLabel": "Situación publicada",
    "planning.stateNotPublished": "La edición oficial seleccionada no publica ninguna fila de estado de desarrollo para este ámbito.",
    "planning.buildNotPublished": "La edición oficial seleccionada no publica ninguna fila de edificabilidad disponible para este ámbito.",
    "planning.absenceNote": "Una ausencia de evidencia publicada, no un cero.",
    "planning.touchedTitle": "Ámbitos de planeamiento que toca la Lente",
    "planning.touchedNote": "Qué ámbitos toca el círculo de Lente. No se calcula ni se insinúa ninguna parte, proporción o porción de sus cantidades publicadas.",
    "planning.touchedNone": "El círculo de Lente no toca ningún ámbito oficial de planeamiento.",
    "planning.touchedCentre": "contiene el centro de la Lente",
    "planning.citizen.title": "Qué significa esto",
    "planning.citizen.what": "Este lugar está dentro de un ámbito oficial de planeamiento: el área en la que el plan general de Madrid recoge el estado de desarrollo y la edificabilidad disponible.",
    "planning.citizen.states": "El plan publica para él cuatro valores de desarrollo separados, que se muestran abajo tal y como se publican.",
    "planning.citizen.build": "También publica cuánta edificabilidad deja disponible allí el plan, por clase de uso, en m² edificable.",
    "planning.citizen.date": "Todo proviene de una única edición oficial fechada, cuya fecha de referencia se muestra junto a las cifras.",
    "planning.citizen.cannot": "Lo que no dice: aquí nada mide la construcción física, los cuatro valores no se combinan en una etapa ni en un porcentaje, no se publica ni se deriva ningún número de viviendas, y ninguna cifra es una parte del círculo de Lente.",
    "planning.ceiling": "Cuatro valores de fase administrativos publicados e independientes y la edificabilidad disponible de planeamiento en m² edificable, de una única edición oficial fechada, para el ámbito completo. Un estado de fase publicado es un estado administrativo, nunca una prueba de construcción física. No existe etapa global, avance, porcentaje ni calendario. No se publica ni se deriva ningún número de viviendas. Ninguna cifra se reparte en el círculo de Lente, el barrio ni ninguna subárea.",
    "planning.source": "Fuente e interpretación",
    "planning.change.title": "Comparación entre ediciones oficiales",
    "planning.change.intro": "Evidencia publicada para este ámbito en dos ediciones oficiales identificadas.",
    "planning.change.previous": "Edición anterior",
    "planning.change.current": "Edición actual",
    "planning.change.datesAria": "Fechas de referencia de las ediciones comparadas",
    "planning.change.scope": "Una diferencia entre publicaciones describe evidencia de planeamiento publicada; no acredita un cambio físico urbano ni su causa.",
    "planning.change.analyst": "Lectura analítica",
    "planning.change.noChange": "No se detecta una diferencia sustantiva publicada entre {previous} y {current}.",
    "planning.change.state": "Cambió el estado publicado",
    "planning.change.new": "Nuevo en esta edición",
    "planning.change.absent": "Ausente de esta edición",
    "planning.change.absenceCauseUnknown": "Causa no resuelta. La documentación oficial no indica un motivo para este código exacto.",
    "planning.change.instrument": "Modificado por instrumento de planeamiento",
    "planning.change.unresolved": "Causa no resuelta",
    "planning.change.nonComparable": "No comparable",
    "planning.change.outcome.s1": "Cuatro campos de fase publicados",
    "planning.change.outcome.s2": "Situación y observaciones publicadas",
    "planning.change.previousValue": "Valor publicado anterior",
    "planning.change.currentValue": "Valor publicado actual",
    "planning.change.instrumentRef": "Instrumento de planeamiento",
    "planning.change.caveat": "La comparación puede no ser homogénea a través de esta modificación del instrumento.",
    "planning.change.numericTitle": "Comparación de edificabilidad disponible",
    "planning.change.observed": "Diferencia publicada observada",
    "planning.change.numericNoChange": "No se detecta una diferencia sustantiva publicada entre {previous} y {current}.",
    "planning.change.withheld": "Comparación numérica retenida",
    "planning.change.situation": "Situación publicada",
    "planning.change.reason": "Motivo",
    "planning.change.reasonUnknown": "Las publicaciones no indican un motivo.",
    "planning.change.reason.pairRecords": "Se requieren los registros de ambas ediciones indicadas.",
    "planning.change.reason.familyMismatch": "Las ediciones no corresponden a la misma familia de fuentes.",
    "planning.change.reason.datesMissing": "Se requieren las fechas de referencia declaradas por la fuente para ambas ediciones.",
    "planning.change.reason.datesOrder": "Las ediciones indicadas deben tener fechas de referencia distintas y ordenadas.",
    "planning.change.reason.identityMissing": "Se requieren la identidad y la huella completa de ambas ediciones.",
    "planning.change.reason.sameEdition": "No se puede proporcionar dos veces la misma edición.",
    "planning.change.reason.eraMismatch": "Las ediciones pertenecen a eras de esquema distintas o no especificadas.",
    "planning.change.reason.recordsMissing": "Se requieren los registros de ambas ediciones.",
    "planning.change.reason.duplicateSituations": "Las etiquetas de situación duplicadas impiden establecer una correspondencia de filas uno a uno.",
    "planning.change.reason.rowSituationMissing": "Una fila publicada no tiene una identidad utilizable de SITUACION DEL ÁMBITO.",
    "planning.change.reason.rowUnmatched": "Una o más filas publicadas no tienen correspondencia en la otra edición.",
    "planning.change.reason.instrumentDocumented": "Se documenta un acto fechado y aplicable de instrumento de planeamiento para un campo comparado.",
    "planning.change.reason.scopedCodeRequired": "Se requiere un código exacto de ámbito vinculado a la edición.",
    "planning.change.reason.noRecordsForCode": "Ninguna de las ediciones indicadas publica un registro para este código exacto.",
    "planning.change.reason.codeAppearsLater": "El código exacto aparece en la edición posterior y no en la anterior.",
    "planning.change.reason.codeAbsentLater": "El código exacto aparece en la edición anterior y no en la posterior.",
    "planning.change.reason.phaseFieldsMissing": "El registro de fase no contiene los cuatro campos publicados requeridos.",
    "planning.change.reason.rowSetMalformed": "El conjunto de filas publicado está mal formado y no se puede clasificar.",
    "planning.change.reason.noClassifierContract": "La familia de fuentes no tiene un contrato de clasificación K7.",
    "planning.change.reason.phaseValuesDiffer": "Uno o más valores de fase S1 publicados difieren entre las ediciones.",
    "planning.change.reason.situationDiffers": "El único valor de situación S2 publicado difiere entre las ediciones.",
    "planning.change.reason.s2Counterpart": "Una o más filas publicadas de S2 no tienen una correspondencia defendible; las ediciones no acreditan un acto de planeamiento.",
    "planning.change.reason.noteCauseUnknown": "Una observación publicada presenta una diferencia sustantiva y las ediciones no indican el motivo.",
    "planning.change.reason.noSubstantiveDifference": "No se detecta una diferencia sustantiva en los campos con correspondencia defendible.",
    "planning.change.reason.codeRequired": "Se requiere un código exacto de ámbito vinculado a la edición.",
    "planning.change.reason.laterOnly": "Ausente de la edición anterior y presente en la posterior.",
    "planning.change.reason.earlierOnly": "Presente en la edición anterior y ausente de la posterior.",
    "planning.change.reason.numericDuplicate": "Las etiquetas de situación duplicadas impiden establecer una correspondencia numérica defendible entre filas.",
    "planning.change.reason.numericSituationMissing": "Una fila no tiene una identidad de situación publicada utilizable.",
    "planning.change.reason.numericUnmatched": "Una o más filas no tienen una correspondencia uno a uno; se retiene la comparación numérica de esas filas.",
    "planning.change.reason.pairNotComparable": "La pareja de ediciones no es comparable.",
    "planning.change.reason.buildabilityRowsMissing": "Ambas ediciones deben publicar filas S2 para este código exacto.",
    "planning.change.reason.numericValuesRequired": "Ambas ediciones deben publicar valores numéricos para la misma clase de uso documentada; una celda vacía no equivale a cero.",
    "planning.change.reason.unmatchedRow": "Esta fila publicada no tiene una correspondencia defendible en la otra edición.",
    "planning.change.reason.someNumericWithheld": "Se retiene al menos una comparación numérica.",
    "planning.change.reason.instrumentNumeric": "Comparación retenida para {reference}; los valores publicados pueden no ser homogéneos.",
    "planning.change.matchingBasis": "Código exacto del ámbito y valor único y estable de SITUACION DEL ÁMBITO en cada edición.",
    "planning.change.rowBasis": "Base de correspondencia de filas",
    "planning.change.provenance": "Procedencia de las ediciones comparadas",
    "planning.change.resource": "Identidad del recurso",
    "planning.change.fingerprint": "Huella SHA-256",
    "planning.change.schemaEra": "Era del esquema",
    "planning.change.source": "Registro de la fuente",
    "planning.change.retrieved": "Obtenido",
    "planning.change.previousEdition": "Anterior",
    "planning.change.currentEdition": "Actual",
    "surface.place.planning.change": "Comparación entre ediciones oficiales",
    "month.1": "ene.", "month.2": "feb.", "month.3": "mar.", "month.4": "abr.",
    "month.5": "may.", "month.6": "jun.", "month.7": "jul.", "month.8": "ago.",
    "month.9": "sept.", "month.10": "oct.", "month.11": "nov.", "month.12": "dic.",
    "metric.tourism": "POI turísticos", "metric.stays": "Hoteles y alojamientos", "metric.mobility": "Nodos de movilidad", "metric.utci": "UTCI media",
    "mix.title": "Mezcla de categorías", "mix.nearest": "Más cercanos en la Lente activa",
    "mix.museums": "Museos", "mix.stays": "Alojamientos", "mix.mobility": "Movilidad", "mix.info": "Información",
    "controls.reset": "Restablecer la Lente activa", "controls.halo": "Halo de comparación", "controls.haloNote": "marcas complementarias del mapa",
    "sources.body": "Fuentes: Ayuntamiento de Madrid — IDEAM (geografía administrativa: distritos, barrios), Subdirección General de Estadística / Padrón Municipal (residentes empadronados) y Censo de Locales (Contexto de hostelería y actividad comercial, instantánea con huella de sep. 2026); Madrid Open Data (museos, información turística, parques principales, contadores permanentes de peatones); EMT Madrid (BiciMAD); CRTM (estaciones de Metro y Cercanías); y Madrid Destino / esmadrid.com (hoteles y otros alojamientos). El catálogo de alojamientos sigue separado de la clase administrativa de locales de la División 55. GitHub Pages usa primero la instantánea de POI más reciente del despliegue para que los marcadores se pinten de inmediato; una pequeña muestra curada del repositorio es el último recurso empaquetado cuando una fuente del despliegue no está disponible. Evidencia fijada del piloto HATI-Madrid (21 ago 2023; el UTCI es salida de modelo, no observación de campo). Contexto del destino: Instituto Nacional de Estadística — encuesta de ocupación hotelera y libro de turismo interno por municipio (solo el municipio de Madrid; los cruces de origen nacional se publican solo por encima de 30 turistas) — véanse la <a href=\"docs/DATA_PROVENANCE.md\">procedencia de los datos</a> y las <a href=\"docs/CLAIMS_AND_LIMITATIONS.md\">afirmaciones y limitaciones</a>. Mapas base: OpenStreetMap/CARTO o Esri World Imagery, según la selección.",
    "legend.halo": "Posiciones fijas: POI turísticos a las 12 · Alojamientos a las 2 · Nodos de movilidad a las 6 · UTCI media a las 9. Las barras finas salen hacia fuera de cada Lente; el número es el valor bruto y la longitud es la densidad frente a una referencia fija de Madrid (el UTCI usa su banda de grados Celsius del modelo). Las longitudes solo se comparan dentro de la misma métrica, nunca entre métricas. No disponible es N/D, nunca cero.",
  }),
});

if (typeof module !== "undefined" && module.exports) {
  module.exports = { SHELL_DICTIONARIES };
}
